### PR TITLE
Merge to incorporate Cyber Chef recipes

### PR DESCRIPTION
**Pull request by ryanoleary26**
## Changes made
Added additional OSINT sources
Minor changes in context menu layout
Added three Cyber Chef recipes
- 'Magic' - run the selection through the magic recipe 
- 'Defang' - defang the selection to make safe for distribution
- 'Resolve domain(s)' - takes a list of domains and resolves their IP addresses

### CODE REVIEW

**Review by zdhenard42 — CHANGES_REQUESTED** [review]
The eventPage.js, menuitems.js, and urlList.js look good. Remove the Readme.md and manifest.json files from your pull request and I will accept them.

**Review by ryanoleary26 — COMMENTED** [review]
Removed readme and manifest.json

**Review by ryanoleary26 — COMMENTED** [review]
Removed readme and manifest.json for active PR #6

**Comment by ryanoleary26** [comment]
@zdhenard42 Just want to check in on this, anything you need me to do further?

**Comment by zdhenard42** [comment]
It appears you are attempting to push deletion of two files. Correct me if I am wrong. If that is the case, close this PR and open a new one with no edits to the readme and manifest. I will push that through once submitted.

**Comment by ryanoleary26** [comment]
Re-submitted in #7, thank you for pointing that out.

**Pull request closed without merging**
