### PR TITLE
Firefox version

### PR DESCRIPTION
**Pull request by sebdufourcq**
2 specific manifest.json for cross-browser compatibilty

### CODE REVIEW

**Comment by zdhenard42** [comment]
Awesome work!! Thank you for being patient with me. I have been tied up with other projects but I will review this over the next few days and provide an update/acceptance.

**Comment by sebdufourcq** [comment]
All functions where cross-compatible, except for the manifest.

Before importing/packaging the extension, the related browser manifest file must be renamed "manifest.json".

Unsigned Firefox extension can be installed on Firefox ESR, Developer edition or Nightly.
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

In order to be signed and available on the official Firefox add-ons site, it must be submitted to Mozilla.

**Comment by sebdufourcq** [comment]
I've added a commit to prevent installation on older version of Firefox that do not support Manifest V3.

**Review by zdhenard42 — APPROVED** [review]
This looks good, thank you for taking the time to port this over to firefox!

**Pull request merged**
